export const actionTypes = {
  LOADING_TRUE: "LOADING_TRUE",
  LOADING_FALSE: "LOADING_FALSE",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  DELETE:"DELETE",
  EDIT:"EDIT",
  ADD_STUDENT:"ADD_STUDENT"
};
