export const actionTypes = {
  LOADING_TRUE: "LOADING_TRUE",
  LOADING_FALSE: "LOADING_FALSE",

  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  RESET: "RESET",

  ADD_STUDENT: "ADD_STUDENT",

  DELETE_STUDENT_INDEX: "DELETE_STUDENT_INDEX",
  EDIT_STUDENT_INDEX: "EDIT_STUDENT_INDEX",

  REMOVE_STUDENT_DATA: "REMOVE_STUDENT_DATA",
  DELETE_STUDENT: "DELETE_STUDENT",

  EDIT_STUDENT: "EDIT_STUDENT",
  REMOVE_STUDENT_DATA_EDIT: "REMOVE_STUDENT_DATA_EDIT",

  FILTER_STUDENT: "FILTER_STUDENT",
  GET_EMPLOYEES: "GET_EMPLOYEES",

  SET_DELETE_EMPLOYEE_ID: "SET_DELETE_EMPLOYEE_ID",
  REMOVE_DELETE_EMPLOYEE: "REMOVE_DELETE_EMPLOYEE",

  REMOVE_UPDATE_EMPLOYEE: "REMOVE_UPDATE_EMPLOYEE",
  SET_UPDATE_EMPLOYEE_ID: "SET_UPDATE_EMPLOYEE_ID",
  FILTERING_EMPLOYEE: "FILTERING_EMPLOYEE",
};
